### ISSUE TITLE
Border & border-color does not work

### ISSUE THREAD

**Issue by loicy** [matheusdavidson/ng-tw#11]
Hello,

First of all, thank you for this lib, it's a very good job!

I can't customize the borders (size and color) in the dropdown (see screenshot).

Another thing I noticed, impossible to put w-full in the dropdown too.

Can I have some info about xposition too?
![Screenshot_147](https://user-images.githubusercontent.com/36493474/180651294-82007f83-409f-4c89-9d71-52f052499043.png)

**Comment by loicy** [comment]
Apologize, its a plugin prob ! ;)

Working good !

**Comment by matheusdavidson** [comment]
Hi there, i'm happy it worked for you. 
Open new issues if you find any problem. =]

Follow me on [twitter](https://twitter.com/mtdade) and star the repository to get latest updates.
